version: 0.0
os: linux

files:
  - source: /Scripts
    destination: /home/ubuntu/myapp

hooks:
  BeforeInstall:
    - location: /home/ubuntu/Scripts/application_stop.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: /home/ubuntu/Scripts/application_start.sh
      timeout: 300
      runas: ubuntu

  ApplicationStop:
    - location: /home/ubuntu/Scripts/application_stop.sh
      timeout: 300
      runas: ubuntu

  ValidateService:
    - location: /home/ubuntu/Scripts/validate_service.sh
      timeout: 300
      runas: ubuntu

