version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Installing dependencies...
      - apt-get update
      - apt-get install -y maven

  pre_build:
    commands:
      - echo Cleaning Maven project...
      - mvn clean

  build:
    commands:
      - echo Building Maven project...
      - mvn install

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:                # Include the appspec.yaml file
    - '**/*'                        # Include all files from the source repo

  discard-paths: yes   # Optional: This will ensure all files are placed in the root directory without subfolder structure
