version: 0.2

phases:
  install:
    commands:
      - echo Installing OpenJDK 11...
      - apt-get update
      - apt-get install -y openjdk-11-jdk  # Or the steps to install Amazon Corretto as mentioned above
  pre_build:
    commands:
      - echo Pre-build phase started
  build:
    commands:
      - echo Build phase started
      - mvn clean install
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - target/demo-1.0-SNAPSHOT.jar  # Adjust this if your artifact name is different
