version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
  pre_build:
    commands:
      - echo Pre-build phase started
  build:
    commands:
      - echo Build phase started
      - mvn clean install
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Moving JAR file to the artifacts directory

artifacts:
  files:
    - target/demo-1.0-SNAPSHOT.jar  # Adjust this if your artifact name is different
  discard-paths: yes  # Optional: discard paths to create a flatter artifact structure
